services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3002
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/data:/app/src/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - PORT=3002
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped